[package]
name = "quiverfs-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
quiverfs-core = { version = "0.1.0", path = "../quiverfs-core" }
